# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "CLI for Confluent Cloud and Confluent Platform"
  homepage "https://docs.confluent.io/confluent-cli/current/overview.html"
  version "4.20.0"

  on_macos do
    on_intel do
      url "https://packages.confluent.io/confluent-cli/archives/4.20.0/confluent_darwin_amd64_disableupdates.tar.gz"
      sha256 "f0a5c2112076eebb7a82575dd406f1a7b8e5c5a33419e4853f33b343e84a009f"

      def install
        bin.install "confluent"
      end
    end
    on_arm do
      url "https://packages.confluent.io/confluent-cli/archives/4.20.0/confluent_darwin_arm64_disableupdates.tar.gz"
      sha256 "be1809cda500fd3a708ef40454c16975a1ee2727fe85248ae1872c81e424c7d1"

      def install
        bin.install "confluent"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://packages.confluent.io/confluent-cli/archives/4.20.0/confluent_linux_amd64_disableupdates.tar.gz"
        sha256 "d5128f2b03c5ade6a76fa5a422fc4b4a1986649775e62e2aed2709ccd78c5252"

        def install
          bin.install "confluent"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://packages.confluent.io/confluent-cli/archives/4.20.0/confluent_linux_arm64_disableupdates.tar.gz"
        sha256 "b35b33d4902922f91f28c02349c6b0b5eb0de8636229e8fa4ccc297746f8c276"

        def install
          bin.install "confluent"
        end
      end
    end
  end

  test do
    system "#{bin}/confluent version"
  end
end
