# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "CLI for Confluent Cloud and Confluent Platform"
  homepage "https://docs.confluent.io/confluent-cli/current/overview.html"
  version "4.40.0"

  on_macos do
    on_intel do
      url "https://packages.confluent.io/confluent-cli/archives/4.40.0/confluent_darwin_amd64_disableupdates.tar.gz"
      sha256 "e9741a2252a56fa78c4d525b0d52af8a07e8372767636d3b51a68d25d68023ed"

      def install
        bin.install "confluent"
      end
    end
    on_arm do
      url "https://packages.confluent.io/confluent-cli/archives/4.40.0/confluent_darwin_arm64_disableupdates.tar.gz"
      sha256 "52c9f658d3b1801f997e13c293b0d8e82fa97273eecd67ec51d7bf83023b6bcf"

      def install
        bin.install "confluent"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://packages.confluent.io/confluent-cli/archives/4.40.0/confluent_linux_amd64_disableupdates.tar.gz"
        sha256 "4f31b1de0dc6ac75df338dcd17303dc9d5ca5d1a096434f6ad504771ee599eb3"

        def install
          bin.install "confluent"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://packages.confluent.io/confluent-cli/archives/4.40.0/confluent_linux_arm64_disableupdates.tar.gz"
        sha256 "2c17a678e0043ca6c70eb10c8a254c7ca9a189cdf776d2ba707d0aa662f9149f"

        def install
          bin.install "confluent"
        end
      end
    end
  end

  test do
    system "#{bin}/confluent version"
  end
end
