# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "CLI for Confluent Cloud and Confluent Platform"
  homepage "https://docs.confluent.io/confluent-cli/current/overview.html"
  version "3.17.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://s3-us-west-2.amazonaws.com/confluent.cloud/confluent-cli/archives/3.17.0/confluent_3.17.0_darwin_arm64_homebrew.tar.gz"
      sha256 "4b9861d8ca8563aa200169bd5e6ad97c023d18460825195af0a2ab9c7bcffc1f"

      def install
        bin.install "confluent"
      end
    end
    if Hardware::CPU.intel?
      url "https://s3-us-west-2.amazonaws.com/confluent.cloud/confluent-cli/archives/3.17.0/confluent_3.17.0_darwin_amd64_homebrew.tar.gz"
      sha256 "e56ea2637deb6c42dcc1d3300a2bb22467f135dabcab0388589c338e068836b8"

      def install
        bin.install "confluent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://s3-us-west-2.amazonaws.com/confluent.cloud/confluent-cli/archives/3.17.0/confluent_3.17.0_linux_amd64_homebrew.tar.gz"
      sha256 "e3ef2d3bc43f4759f91f551dcd43824dcf51f31495ab85e829a7b5d2ad4b0ab1"

      def install
        bin.install "confluent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://s3-us-west-2.amazonaws.com/confluent.cloud/confluent-cli/archives/3.17.0/confluent_3.17.0_linux_arm64_homebrew.tar.gz"
      sha256 "2e7d0ff2e9d273253d2383932382e62c343cfac156504bc4a469cfb96fe9fc96"

      def install
        bin.install "confluent"
      end
    end
  end

  test do
    system "#{bin}/confluent version"
  end
end
